Repository kubernetes-csi/csi-test, pull requests merged in 2018-10, with the labels that each got.

#122 Update mock driver for testing
  driver/driver.go
  mock/main.go
  mock/service/controller.go
  mock/service/identity.go
  mock/service/node.go
  mock/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#125 Add volume parameters to sanity tests
  cmd/csi-sanity/sanity_test.go
  pkg/sanity/controller.go
  pkg/sanity/sanity.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#128 Fix canary builds
  .travis.yml
  utils/safegoroutinetester.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
