Repository kubernetes-csi/csi-test, pull requests merged in 2018-09, with the labels that each got.

#105 pkg/sanity: Use a single grpc connection via caching in SanityContext
  hack/_apitest/api_test.go
  hack/_embedded/embedded_test.go
  hack/e2e.sh
  pkg/sanity/sanity.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#110 Add tests for long names
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#116 Fix snapshot test
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/S

#117 Update README for sanity test using Ginkgo.
  .gitignore
  pkg/sanity/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#115 remove test case for starting_token when ListSnapshots
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S
