Repository kubernetes-csi/csi-test, pull requests merged in 2018-11, with the labels that each got.

#134 Add support for attach limits to the mock driver
  mock/main.go
  mock/service/node.go
  mock/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#133 Fix listsnapshot clean up
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#138 Update to v1.0.0-RC2 of CSI
  Gopkg.lock
  Gopkg.toml
  driver/driver.go
  driver/driver.mock.go
  hack/e2e.sh
  mock/cache/SnapshotCache.go
  mock/service/controller.go
  mock/service/identity.go
  mock/service/node.go
  mock/service/service.go
  pkg/sanity/cleanup.go
  pkg/sanity/controller.go
  pkg/sanity/identity.go
  pkg/sanity/node.go
  test/co_test.go
  test/driver_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/golang/protobuf/LICENSE
  vendor/github.com/golang/protobuf/proto/encode.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/proto/text.go
  vendor/github.com/golang/protobuf/proto/text_parser.go
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
  vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#139 Add PUBLISH_READONLY capability to Controller Caps
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#140 Update v0.3.0 branch to release 0.3.0-4
  .gitignore
  CONTRIBUTING.md
  OWNERS
  README.md
  SECURITY_CONTACTS
  hack/_apitest/api_test.go
  hack/_embedded/embedded_test.go
  hack/e2e.sh
  pkg/sanity/controller.go
  pkg/sanity/sanity.go
Labels: cncf-cla: yes, lgtm, size/L

#141 Fix controller publish in readonly mode
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#145 Add ControllerServiceCapability_RPC_CLONE_VOLUME to GetCapabilities.
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
