Repository kubernetes-csi/csi-test, pull requests merged in 2019-07, with the labels that each got.

#205 Closes #204 - Treat list volume tokens as opaque
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/L

#208 Tolerate nil capabilities for plugins that don't provide CONTROLLER_SERVICE
  pkg/sanity/controller.go
  pkg/sanity/identity.go
  pkg/sanity/node.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#209 ephemeral volumes
  cmd/mock-driver/main.go
  mock/service/node.go
  mock/service/service.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#210 cleanup fix + enhancement
  pkg/sanity/cleanup.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#211 Add 2.1 changelog
  CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
