Repository kubernetes-csi/csi-test, pull requests merged in 2019-04, with the labels that each got.

#186 grammar fixes for snapshot tests
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#187 sanity: use correct path during cleanup
  pkg/sanity/cleanup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#184 prow testing
  .prow.sh
  release-tools/.prow.sh
  release-tools/README.md
  release-tools/build.make
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/util.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#189 Prow testing: update csi-release-tools
  release-tools/build.make
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#190 Prow testing: update csi-release-tools, fix reporting
  .prow.sh
  Makefile
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#192 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#191 update to Go 1.12.4
  hack/e2e.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#193 Reuse testing api
  Gopkg.lock
  pkg/sanity/cleanup.go
  pkg/sanity/controller.go
  pkg/sanity/node.go
  pkg/sanity/sanity.go
  pkg/sanity/tests.go
  utils/grpcutil.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L
