Repository kubernetes-csi/csi-test, pull requests merged in 2020-05, with the labels that each got.

#264 Bump up the csi spec version mention from 0.4.0 to 1.2.0
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#257 Add descriptions to To() expectations in NodeUnpublishVolume
  pkg/sanity/node.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/XS

#267 Update release-tools to support building on Mac OS X
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#258 Remove missing volume test case for NodeUnpublishVolume
  pkg/sanity/node.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, release-note, size/S
