Repository kubernetes-csi/csi-test, pull requests merged in 2020-09, with the labels that each got.

#289 Cleanup snapshots before volumes
  pkg/sanity/resources.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#290 Add changelog for 4.0.1
  CHANGELOG-4.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#292 sanity: add missing TestVolumeParameters to CreateVolume calls
  pkg/sanity/controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS
