Repository kubernetes-csi/csi-test, pull requests merged in 2020-11, with the labels that each got.

#303 Create target directory if it doesn't exist
  mock/service/node.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#306 Add v4.0.2 changelog and move all changelogs into a directory
  CHANGELOG/CHANGELOG-2.1.md
  CHANGELOG/CHANGELOG-2.2.md
  CHANGELOG/CHANGELOG-2.3.md
  CHANGELOG/CHANGELOG-3.0.md
  CHANGELOG/CHANGELOG-3.1.md
  CHANGELOG/CHANGELOG-4.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#307 Cherry pick #303 to release-3.1: Create target dir if it doesn't exist
  mock/service/node.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#309 release notes for v3.1.2
  CHANGELOG-3.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#312 Update release tools
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#313 update klog to v2.4.0
  cmd/mock-driver/main.go
  driver/driver.go
  go.mod
  go.sum
  mock/service/service.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XXL
