Repository kubernetes-csi/csi-test, pull requests merged in 2024-08, with the labels that each got.

#538 Add ControllerModifyVolume RPC sanity tests
  .gitignore
  Makefile
  cmd/csi-sanity/main.go
  hack/e2e.sh
  pkg/sanity/controller.go
  pkg/sanity/groupcontroller.go
  pkg/sanity/node.go
  pkg/sanity/sanity.go
  pkg/sanity/util.go
Labels: kind/feature, cncf-cla: yes, size/XL, lgtm, release-note, approved, ok-to-test

#534 Add VolumeContext in ControllerPublishVolume
  pkg/sanity/controller.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS, ok-to-test

#497 Check ContentSource when creating volume from snapshot
  pkg/sanity/controller.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note, approved, size/XS, ok-to-test

#550 Add changelog for v5.3.0
  CHANGELOG/CHANGELOG-5.3.md
Labels: cncf-cla: yes, size/M, lgtm, kind/documentation, release-note-none, approved

#553 Add Protobuf Matcher utility
  go.mod
  utils/protobuf_matcher.go
Labels: cncf-cla: yes, size/M, lgtm, release-note-action-required, approved
